---
apiVersion: v1
kind: Service
metadata:
  name: rust-app
  namespace: default
spec:
  type: ClusterIP
  # type: LoadBalancer
  selector:
    app: rust-app
  ports:
    - port: 8000
      name: handler-name
